### ISSUE TITLE
username is split by dash

### ISSUE THREAD

**Issue by hrez** [AppliedTrust/traildash#11]
Hi,

It splits usernames with dash(es) "-" in the name. For example user corp-user-dw would become three users  corp, user and dw. Is there an easy way to fix it?

**Comment by nmcclain** [comment]
I can reproduce this problem.  It seems that this is "expected" behavior of ElasticSearch, and the suggested workaround is to store a raw version fo the field in the ES index for use by Kibana: https://github.com/elastic/kibana/issues/364

I can take a look at implementing this in the coming weeks, but also greatly welcome a PR!

**Comment by hrez** [comment]
Looks like there are many ways to approach this.
One way is to apply mapping to empty elasticsearch index. You can't apply it on populated index. 
It would need to be re-indexed (which is what I ended-up doing with the help of elasticdump). 

Here is a mapping I used:

``` json
PUT /cloudtrail
{
      "mappings": {
         "event": {
            "properties": {
               "UserIdentity": {
                  "properties": {
                     "userName": {
                        "type": "string",
                        "index": "not_analyzed"
                     }
                  }
               }
            }
         }
      }
}
```

**Comment by nmcclain** [comment]
It seems like it would be easy to have traildash check for an empty index on start, and add that mapping before inserting records.  I'll plan to add this feature.

**Comment by nmcclain** [comment]
I still plan to add this once we figure out the critical errors in issue #21.

**Comment by ulsa** [comment]
Any status on this?

**Comment by nmcclain** [comment]
I'm still holding out for critical issue #21...

I would be happy to accept a pull request for this however!

**Comment by nmcclain** [comment]
Traildash has been retired since AWS now offers a built-in solution based on the same technology (ElasticSearch and Kibana): https://aws.amazon.com/blogs/aws/cloudwatch-logs-subscription-consumer-elasticsearch-kibana-dashboards/
