### ISSUE TITLE
Split elasticsearch index

### ISSUE THREAD

**Issue by atward** [AppliedTrust/traildash#16]
Having a single 'cloudtrail' index can grow quite large. logstash splits indexes by date eg: logstash-2014-05-12.

Can something like this be investigated? It would assist with maintenance/administration.

**Comment by nmcclain** [comment]
I 100% agree this is an important feature.  Will make it happen.

**Comment by nmcclain** [comment]
I still plan to add this once we figure out the critical errors in issue #21.

**Comment by nmcclain** [comment]
Traildash has been retired since AWS now offers a built-in solution based on the same technology (ElasticSearch and Kibana): https://aws.amazon.com/blogs/aws/cloudwatch-logs-subscription-consumer-elasticsearch-kibana-dashboards/
