### ISSUE TITLE
Error downloading from S3: Get : 301 response missing Location header

### ISSUE THREAD

**Issue by jmreicha** [AppliedTrust/traildash#17]
I ran the backfill.py script to populate my SQS queue but the traildash container that I am running seems to be having issues downloading the messages.

I am seeing tons of errors in the logs for the container.

```
Fetched sqs:// [s3:XXX.json.gz]
Error downloading from S3: Get : 301 response missing Location header
```

Am I missing something?

**Comment by jmreicha** [comment]
Digging a little bit further it looks like the AWS region is not getting set correctly.  Here is the bit in my configuration I'm using to set the region in the docker command:

`-e "AWS_REGION=us-east-1"`

Does that look right?

**Comment by jszwedko** [comment]
I'm seeing this as well.

**Comment by jszwedko** [comment]
Turned out to be because my SQS queue and S3 bucket were in different regions.

**Comment by nmcclain** [comment]
So the short-term fix is to ensure the SQS queue and S3 bucket is in the same region (for the CloudTrail config for ALL regions).  The long-term fix is to make this code support different regions.

**Comment by bpsmit28** [comment]
So what do we do for an instance where the bucket was already setup?

**Comment by jszwedko** [comment]
@bpsmit28 we ended up just copying the bucket

**Comment by nmcclain** [comment]
Traildash has been retired since AWS now offers a built-in solution based on the same technology (ElasticSearch and Kibana): https://aws.amazon.com/blogs/aws/cloudwatch-logs-subscription-consumer-elasticsearch-kibana-dashboards/
