### ISSUE TITLE
Pull in cloudtrail history

### ISSUE THREAD

**Issue by thenayr** [AppliedTrust/traildash#2]
First of all, THANK YOU!!! I knew somebody had to be working on a tool like this and waited patiently for the solution ;) 

This is exactly what I had hoped for and then some..

Back to the issue at hand:  Can I pull in history prior to the installation of this dashboard?   

Thanks again!

**Comment by nmcclain** [comment]
This tool should pull in any history for which there are SQS messages.  One way to achieve this would be to use a script to create SQS messages for old S3 files.  Unfortunately, this script doesn't currently exist.

Open to a pull request or suggestions other approaches.

**Comment by thenayr** [comment]
@nmcclain Thanks, caught that shortly after publishing this issue.  Didn't have SQS enabled for cloudtrail prior to setting up traildash.  I will close this out for the time being ;)

**Comment by Tenzer** [comment]
I made a Python script using the boto3 library to backfill data for us. It simply works by listing the files in the S3 bucket you insert in the script, and then creates SNS messages for the files it finds, like S3 normally would do when new files are added. You can find it here: https://gist.github.com/Tenzer/bf6f400514839d651d21.

I couldn't really see any obvious locations to add the script in the repository (and perhaps you prefer a program written in Go?), but let me know if you would like a pull request to get it added to the repository, otherwise I guess a link to the Gist in the README file also could work.

**Comment by nmcclain** [comment]
This is awesome @Tenzer - please make a PR to add the script to the root of the repo.  I'd also appreciate it if you could add a note to the README file about how to use it.

**Comment by Tenzer** [comment]
Sure, I think I'll just brush up the script so it will adhere to the same environment variables that Traildash uses, and probably also see if I can get it to send messages directly to SQS instead of around SNS, just to keep things simpler.

**Comment by nmcclain** [comment]
Well done @Tenzer - closing.

**Comment by jmreicha** [comment]
Are there instructions somewhere for running this?  I _think_ I have the variables set up correctly but am getting errors and I'm not sure what to look at.

```
Traceback (most recent call last):
  File "./backfill.py", line 13, in <module>
    bucket = boto3.resource('s3').Bucket(environ.get('AWS_S3_BUCKET'))
  File "/usr/local/lib/python2.7/dist-packages/boto3/resources/factory.py", line 310, in create_resource
    client=self.meta.client)(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/boto3/resources/base.py", line 116, in __init__
    'Required parameter {0} not set'.format(identifier))
ValueError: Required parameter name not set
```

**Comment by jmreicha** [comment]
Nevermind, should have played with it a little bit more.

I had not exported `AWS_S3_BUCKET` and `AWS_SQS_URL` environment variables.  Items are backfilling in to SQS now with those values added.

**Comment by Tenzer** [comment]
I guess some error handling - or at least just verification of the environment variables - would be in order. I'm not really a fan of programs that give a stack trace back for problems that can easily be caught with a bit of checking. With that in mind I have made a PR in #18 which should catch those errors and output a nicer error message.

**Comment by jmreicha** [comment]
@Tenzer I was thinking of doing something similar but am glad you beat me to it.

**Comment by Manakw** [comment]
Any guidance on how to use it would be of great help. I have traildash up and running

**Comment by Tenzer** [comment]
@Manakw There's some instructions in the [README file](https://github.com/AppliedTrust/traildash#backfilling-data). Is that sufficient?

**Comment by Manakw** [comment]
When i try to run it, it gives me an error "botocore.exceptions.NoRegionError: You must specify a region". But i have a env variable with AWS_REGION already?

**Comment by Tenzer** [comment]
Hmm, that seems odd. An alternative way to specify the region is to place a file at `~/.aws/config` containing something like the following (of course with the right region):

```
[default]
region=eu-west-1
```

Perhaps that will work for you?

**Comment by Manakw** [comment]
@Tenzer Seems like my version of aws-cli was broken which was causing issues. It works perfectly now. Thanks
