### ISSUE TITLE
Unable to delete Dashboards via kibana

### ISSUE THREAD

**Issue by cuotos** [AppliedTrust/traildash#22]
If I try and delete a dashboard that I have created, I get a 403 forbidden from kibana. 

Remote Address:xxx:xxx:xxx:xxx:80
Request URL:http://traildash.xxxxxx.com/es/kibana-int/dashboard/TESTDASH
Request Method:DELETE
Status Code:403 Forbidden

workaround if ES port is accessible is to manually "DELETE :9200/kibana-init/dashboard/TESTDASH"

**Comment by rainmanh** [comment]
Hi

Just in case you are missing this bit:

```
ElasticSearch proxy ensures your logs are secure and read-only
No need to open direct access to your ElasticSearch instance
Helps to achieve PCI and HIPAA compliance in the cloud
```

@cuotos , I have opened the following issue : "panic: runtime error: index out of range"
have you experienced anything like it?
I am running the script out of docker and I just get that. I am not sure why is that for..

Thanks!!

**Comment by cuotos** [comment]
My mistake. I had read that but had forgotten. 

@rainmanh, No I haven't seen that error.

**Comment by nmcclain** [comment]
This is working as intended - I think it is better to error towards compliance, even if that means deleting dashboards takes an extra step.
