### ISSUE TITLE
Error downloading from S3: Error unmarshaling cloutrail JSON

### ISSUE THREAD

**Issue by rahulmehrotra1** [AppliedTrust/traildash#27]
Hi,
I am getting the following error when trying to use traildash

``` shell
Fetched sqs://(SQSurl).json.gz]
 Error downloading from S3: Error unmarshaling cloutrail JSON: invalid character '\x1f' looking for beginning of value 
```

I am unable to identify the cause of this issue. I have checked the credentials and access rights and I am sure they are correct. The sqs url is correct too as traildash is able to fetch the data.

**Comment by nmcclain** [comment]
Sorry for the trouble.  Traildash has been retired since AWS now offers a built-in solution based on the same technology (ElasticSearch and Kibana): https://aws.amazon.com/blogs/aws/cloudwatch-logs-subscription-consumer-elasticsearch-kibana-dashboards/
