### ISSUE TITLE
Missing error field and question on documentation claims

### ISSUE THREAD

**Issue by bfleming-ciena** [AppliedTrust/traildash#30]
Finding it difficult to get this noted feature working:

"What idiot added 0.0.0.0/0 to the security group?"

Also noticed that the the field errorMessage is not included. This is key in detecting unauthorization attempts. Also errorCode: "AccessDenied"

**Comment by kevinpauli** [comment]
:+1: Where is the "Recent Changes" panel shown in the screen shot?

**Comment by nmcclain** [comment]
Sorry for the belated response folks.  Traildash has been retired since AWS now offers a built-in solution based on the same technology (ElasticSearch and Kibana): https://aws.amazon.com/blogs/aws/cloudwatch-logs-subscription-consumer-elasticsearch-kibana-dashboards/
