### ISSUE TITLE
Little better docs on building

### ISSUE THREAD

**Issue by bfleming-ciena** [AppliedTrust/traildash#31]
I'm not familiar with golang and related tools, so maybe it's obvious how to build traildash if you know golang.  I'm having to hack away at getting traildash to build.

I installed ubuntu, downloaded glock, put it in my path. Confused about GOPATH a little.  Long story short I ended up with this after running make release.

go build github.com/appliedtrust/traildash: signal: killed

**Comment by danielcbright** [comment]
:+1: 

I also need some better docs on how to run this on Centos, I can't use docker for various reasons and will have to run it natively.

**Comment by nmcclain** [comment]
Traildash has been retired since AWS now offers a built-in solution based on the same technology (ElasticSearch and Kibana): https://aws.amazon.com/blogs/aws/cloudwatch-logs-subscription-consumer-elasticsearch-kibana-dashboards/
