### ISSUE TITLE
Add S3 logging

### ISSUE THREAD

**Issue by bfleming-ciena** [AppliedTrust/traildash#32]
How difficult would it be to get S3 logs in there as well?  We can get the events in the sqs queue.

https://aws.amazon.com/blogs/aws/s3-event-notification/

**Comment by nmcclain** [comment]
Traildash has been retired since AWS now offers a built-in solution based on the same technology (ElasticSearch and Kibana): https://aws.amazon.com/blogs/aws/cloudwatch-logs-subscription-consumer-elasticsearch-kibana-dashboards/

This should definitely be possible with their solution!
