### ISSUE TITLE
Inner JSON Unmarshal error: invalid character 'C' looking for beginning of value

### ISSUE THREAD

**Issue by atward** [AppliedTrust/traildash#4]
Running traildash reports issues with certain messages produced by cloudtrail

```
2015/03/11 13:56:42 Error dequeing from SQS: Inner JSON Unmarshal error [id: 144fb3b5-2dba-55d7-a35a-fecc58113ad7]: invalid character 'C' looking for beginning of value
2015/03/11 13:58:51 Error dequeing from SQS: Inner JSON Unmarshal error [id: 34c36589-12f7-5470-83d1-28f067450eaf]: invalid character 'C' looking for beginning of value
```

Digging shows this message is the initial Cloudtrail validation message, which should be skipped/ignored/auto-accepted.

```
2015/03/11 13:58:51 full message: CloudTrail validation message.
```

**Comment by nabeelamjad** [comment]
I noticed a similar issue when copying Cloudtrail logs from a different bucket (in a different AWS account) into mine and using the SQS notification on object creation to fetch these, compared the *.json.gz files and they had similar file properties however it would keep giving 
`2015/03/11 07:13:49 Error dequeing from SQS: Inner JSON Unmarshal error [id: ]: unexpected end of JSON input`

**Comment by nmcclain** [comment]
Thanks for the report @atward. It should be easy to swallow this message - will post an update soon.

**Comment by nmcclain** [comment]
The "CloudTrail validation message" fix is implemented in the latest release: https://github.com/AppliedTrust/traildash/releases/tag/v0.0.9

**Comment by navidurrahman** [comment]
Is this fix updated in docker container?
