### ISSUE TITLE
SQS Long polling

### ISSUE THREAD

**Issue by Tenzer** [AppliedTrust/traildash#5]
I was wondering if it wouldn't make sense to use [SQS long polling](http://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/sqs-long-polling.html), instead of just sleeping for a minute if there are no changes? It should mean that there is less delay between the items coming into the SQS queue and Traildash handling them, without putting much load on either end.

**Comment by nmcclain** [comment]
I agree and am happy to do implement this.

One gotcha: the max SQS long-polling time is 20 seconds.  So, "constant" long-polling will require 3x as many queries as the current "once per minute" strategy.  Seems worth it.

**Comment by nmcclain** [comment]
This is implemented in the latest release: https://github.com/AppliedTrust/traildash/releases/tag/v0.0.9

**Comment by Tenzer** [comment]
Awesome, I just updated and it seems to work :)
