### ISSUE TITLE
Having problems getting traildash to run

### ISSUE THREAD

**Issue by Thermatix** [AppliedTrust/traildash#8]
I can't run traildash via docker as our infrastructure isn't ready for that yet so I'm installing it via `go get github.com/AppliedTrust/traildash` and running it directly from the commandline (well, via chef any way on a VM box via vagrant) and then I forward the port I'm running the kibana board on port 80 to port 8000 on my host and try to access it.

All that happens is that I get is the board but with nothing on it (sometimes it does display values) and the url changes to `http://localhost:8000/#/connectionFailed` and then traildash dies, when I run it directly with `traildash` I get:

```
2015/03/19 12:25:51 Started
2015/03/19 12:25:51 web server exit
```

it does log out either:

```
2015/03/19 12:27:42 Empty queue... polling for 20 seconds.
```

or sometimes about pulling and deleting sqs information from Cloudtrail but I can't access the kibana board from the host or on the box (by doing `curl localhost:80`).

We have the following settings on elasticsearch btw:

```
http.cors.enabled: true
http.cors.allow-origin: "*"
```

Also I'm not seeing any errors about connecting to elasticsearch in the logging output.

I'm not sure what to do next.

**Comment by nmcclain** [comment]
I think the problem is that you need to take some special steps to bundle Kibana and a customized Kibana config file into the binary when you build it.  Two alternatives you could try:
1. Use the release from here, which includes Kibana in the binary: https://github.com/AppliedTrust/traildash/releases 
2. Run these commands before building (these are from the Makefile):

```
curl -s https://download.elasticsearch.org/kibana/kibana/kibana-3.1.2.tar.gz | tar xvz -C .
mv kibana-3.1.2 kibana
cp assets/config.js kibana/config.js
cp assets/CloudTrail.json kibana/app/dashboards/default.json
go-bindata -pkg="main" kibana/...
```

Let me know how it goes!

**Comment by Thermatix** [comment]
Well, I just tried it and no dice, it still bleats about connection failed.

**Comment by Thermatix** [comment]
I'm having trouble, whenever I try to run the MakeFile Glock just errors with unable to find the `GLOCKFILE` even though I can physically see it, I even changed it's mode to 777 and yet still it errors.

**Comment by disassembler** [comment]
This looks like your missing glock. Do you have glock installed?

go get github.com/robfig/glock

with that and traildash installed using:
go get github.com/AppliedTrust/traildash

you should be able to run glock install to get the hooks added to the repo:
glock install github.com/AppliedTrust/traildash

**Comment by Thermatix** [comment]
The problem was that the folder was spelt `AppliedTrust` when it was looking for `appliedtrust` >_<, bah, freaking capitals! Any way, No dice, still erroring with connection failed when run through chef and when run directly still doing :

```
2015/03/20 15:30:50 Started
2015/03/20 15:30:50 web server exit
```

**Comment by Thermatix** [comment]
ok, I got it working, not sure what I did but it's working (somtimes I don't pay attention to what I'm doing, bad habit), I did however remove the steps that @nmcclain mentioned so what I did to get it working didn't involve that. 
Thanks for the help though.
