### ISSUE TITLE
Multiple AWS Account support

### ISSUE THREAD

**Issue by nabeelamjad** [AppliedTrust/traildash#9]
Hi Traildash Dev Team,

First of all thanks a lot for this amazing package, it saves us a lot of trouble crawling through logs. I was wondering if it is possible in its current state to specify multiple AWS accounts (with different credentials/region) to poll data/logs from?  Currently it seems all CT logs indicate Account ID (in case a confusion arises which event is for which account).

Thanks in advance!

**Comment by matthewrkrieger** [comment]
This can definitely be done! I am putting together a documentation pull request to explain the process which we will roll out shortly.

**Comment by nabeelamjad** [comment]
Cool, thanks a lot!
